### ISSUE TITLE
Check if there are precommit checks for rego files

### ISSUE THREAD

**Issue by fredrkl** [fredrkl/gh-terraform-flows#8]

**Comment by anderseknert** [comment]
There are :) https://github.com/anderseknert/pre-commit-opa

I'd recommend taking a look at [Regal](https://github.com/styrainc/regal) as well, which also provides pre-commit hooks.

**Comment by fredrkl** [comment]
Thank you @anderseknert! I did not expect to get feedback from the Styra developer advocate!
